# Generated by Django 4.2.3 on 2023-07-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerTable',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_first_name', models.CharField(max_length=255)),
                ('owner_last_name', models.CharField(max_length=255)),
                ('owner_phone_1', models.CharField(max_length=255)),
                ('owner_phone_2', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_email', models.EmailField(max_length=255)),
                ('owner_department', models.CharField(max_length=255)),
                ('owner_city', models.CharField(max_length=255)),
                ('owner_address', models.CharField(max_length=255)),
                ('owner_profession', models.CharField(max_length=255)),
                ('owner_NIF', models.CharField(max_length=255)),
                ('owner_cin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_slogan', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('hash_password', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies_accounts.ownertable')),
            ],
        ),
    ]
