# Generated by Django 4.2.3 on 2023-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='patent_number',
            field=models.CharField(default='none', max_length=255, unique=True),
        ),
    ]
