# Generated by Django 4.2.3 on 2023-08-22 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies_accounts', '0002_companyprofile_patent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
