# Generated by Django 4.2.3 on 2023-08-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_alter_offertype_offer_type_name'),
        ('accounts', '0011_alter_passwordchange_phone_number_for_new_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorseDescriptionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.JSONField()),
                ('odd_min', models.FloatField()),
                ('number_of_horses_allowed', models.IntegerField()),
                ('bonus', models.FloatField()),
                ('jackpot', models.FloatField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.launchedoffer')),
            ],
        ),
        migrations.CreateModel(
            name='HorseGameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds_game', models.FloatField()),
                ('horse_selected', models.JSONField()),
                ('maximum_payout', models.FloatField()),
                ('status_result', models.CharField(max_length=255)),
                ('description_horse_race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horse_race_app.horsedescriptiongame')),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gamblerprofile')),
            ],
        ),
    ]
