# Generated by Django 4.2.3 on 2023-08-02 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_accounts', '0002_companyprofile_patent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalCompanies',
            fields=[
                ('withdrawal_id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_amount', models.FloatField()),
                ('withdrawal_phone_number', models.CharField(max_length=255)),
                ('withdrawal_method', models.CharField(max_length=255)),
                ('withdrawal_status', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_accounts.companyprofile')),
            ],
        ),
    ]
