# Generated by Django 4.2.3 on 2023-07-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance_globale', models.FloatField()),
                ('balance_transfert', models.FloatField()),
                ('balance_bonus', models.FloatField()),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gamblerprofile')),
            ],
        ),
    ]
