# Generated by Django 4.2.3 on 2023-07-29 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 29, 20, 46, 11, 6390, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_bonus',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_globale',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='balance_transfert',
            field=models.FloatField(null=True),
        ),
    ]
