# Generated by Django 4.2.3 on 2023-08-02 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_handler', '0002_balance_balance_date_alter_balance_balance_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 14, 57, 5, 861230, tzinfo=datetime.timezone.utc)),
        ),
    ]
