# Generated by Django 4.2.3 on 2023-08-09 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_handler', '0009_alter_balance_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 16, 35, 59, 899766, tzinfo=datetime.timezone.utc)),
        ),
    ]
