# Generated by Django 4.2.3 on 2023-07-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamblerProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordChange',
            fields=[
                ('change_password_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number_for_new_password', models.CharField(max_length=255)),
                ('code_generated_for_new_password', models.CharField(max_length=255)),
                ('hash_new_password', models.CharField(max_length=500)),
                ('changed_password_date', models.DateTimeField(auto_now_add=True)),
                ('gambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gamblerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GamblerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
                ('sex', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.gamblerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
