# Generated by Django 4.2.3 on 2023-07-29 15:06

import accounts.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gambleruser_is_staff_alter_gambleruser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamblerprofile',
            name='phone_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 8 digits long.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='gambleruser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2023, 7, 29), validators=[accounts.models.GamblerUser.validate_past_date, accounts.models.GamblerUser.validate_reasonable_date]),
        ),
        migrations.AlterField(
            model_name='gambleruser',
            name='phone_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be exactly 8 digits long.', regex='^\\d{8}$')]),
        ),
    ]
