# Generated by Django 4.2.3 on 2023-07-29 15:22

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_gamblerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamblerprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2023, 7, 29), null=True, validators=[accounts.models.GamblerProfile.validate_past_date, accounts.models.GamblerProfile.validate_reasonable_date]),
        ),
        migrations.AlterField(
            model_name='gamblerprofile',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gambleruser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2023, 7, 29), null=True, validators=[accounts.models.GamblerUser.validate_past_date, accounts.models.GamblerUser.validate_reasonable_date]),
        ),
        migrations.AlterField(
            model_name='gambleruser',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=255, null=True),
        ),
    ]
