# Generated by Django 4.2.3 on 2023-07-29 15:26

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_gamblerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamblerprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True, validators=[accounts.models.GamblerProfile.validate_past_date, accounts.models.GamblerProfile.validate_reasonable_date]),
        ),
    ]
