# Generated by Django 4.2.3 on 2023-07-29 15:27

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_gamblerprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambleruser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, null=True, validators=[accounts.models.GamblerUser.validate_past_date, accounts.models.GamblerUser.validate_reasonable_date]),
        ),
    ]
