# Generated by Django 4.2.3 on 2023-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_gambleruser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchange',
            name='expiration_time',
            field=models.DateTimeField(default='1900-01-01'),
        ),
    ]
