# Generated by Django 4.2.3 on 2023-07-29 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordchange_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchange',
            name='expiration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
