# Generated by Django 4.2.3 on 2023-08-04 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_accounts', '0002_companyprofile_patent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_offer_min', models.FloatField()),
                ('gain_offer_max', models.FloatField()),
                ('offer_launched_status', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_accounts.companyprofile')),
                ('offer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offertype')),
            ],
        ),
    ]
