# Generated by Django 4.2.3 on 2023-08-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_accounts', '0002_companyprofile_patent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositCompanies',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_date', models.DateField()),
                ('deposit_phone_number', models.CharField(max_length=255)),
                ('deposit_method', models.CharField(max_length=255)),
                ('deposit_amount', models.FloatField()),
                ('deposit_status', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_accounts.companyprofile')),
            ],
        ),
    ]
