# Generated by Django 4.2.3 on 2023-08-09 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0002_alter_offertype_offer_type_name'),
        ('accounts', '0011_alter_passwordchange_phone_number_for_new_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGambler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_payout', models.FloatField()),
                ('status_result', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FootballEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_options_per_match', models.IntegerField()),
                ('odds_min', models.FloatField()),
                ('odds_max', models.FloatField()),
                ('number_max_to_lose', models.IntegerField()),
                ('percentage_loss_offer', models.FloatField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.launchedoffer')),
            ],
        ),
        migrations.CreateModel(
            name='MatchGambler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('league_name', models.CharField(max_length=255)),
                ('fixure_id_api', models.BigIntegerField()),
                ('league_country', models.CharField(max_length=255)),
                ('choicegambler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.choicegambler')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('start_time', models.TimeField()),
                ('league_name', models.CharField(max_length=255)),
                ('fixure_id_api', models.BigIntegerField()),
                ('league_country', models.CharField(max_length=255)),
                ('footballevent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.footballevent')),
            ],
        ),
        migrations.AddField(
            model_name='choicegambler',
            name='footballevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.footballevent'),
        ),
        migrations.AddField(
            model_name='choicegambler',
            name='gambler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gamblerprofile'),
        ),
        migrations.AddField(
            model_name='choicegambler',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.launchedoffer'),
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bookmaker_id_api', models.BigIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmakers', to='football_app.match')),
            ],
        ),
        migrations.CreateModel(
            name='BetGambler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betsGambler', to='football_app.matchgambler')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('odd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football_app.bookmaker')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='football_app.match')),
            ],
        ),
    ]
