# Generated by Django 4.2.3 on 2023-08-02 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_accounts', '0002_companyprofile_patent_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceCompanies',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance_globale', models.FloatField(null=True)),
                ('balance_date', models.DateTimeField(default=datetime.datetime(2023, 8, 2, 19, 32, 8, 393340, tzinfo=datetime.timezone.utc))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies_accounts.companyprofile')),
            ],
        ),
    ]
