# Generated by Django 4.2.3 on 2023-08-02 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_handler_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecompanies',
            name='balance_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 20, 39, 18, 79439, tzinfo=datetime.timezone.utc)),
        ),
    ]
