# Generated by Django 4.2.3 on 2023-08-03 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_handler_companies', '0002_alter_balancecompanies_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecompanies',
            name='balance_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 2, 18, 52, 850674, tzinfo=datetime.timezone.utc)),
        ),
    ]
